from typing import Dict, Any
from datetime import datetime


def generate_markdown(report: Dict[str, Any]) -> str:
    company = report.get("company_name", "Company")
    tagline = report.get("tagline", "")
    lines = []

    lines.append(f"# {company} — Company Intelligence Report")
    if tagline:
        lines.append(f"> *\"{tagline}\"*")
    lines.append(f"\n*Generated by CompanyIQ · {datetime.now().strftime('%B %d, %Y')}*\n")
    lines.append("---\n")

    lines.append("## Table of Contents")
    toc = [
        "Company Overview", "Founders & Leadership", "Origin Story & Timeline",
        "Past Challenges", "Current Projects", "Future Roadmap",
        "Competitive Landscape", "Struggles Turned Success",
        "Interview Preparation", "Culture & Work Environment",
        "Red Flags & Due Diligence", "Application Strategy",
        "Candidate Fit Analysis",
    ]
    for i, t in enumerate(toc, 1):
        anchor = t.lower().replace(" ", "-").replace("&", "").replace("'", "").replace(",", "")
        lines.append(f"{i}. [{t}](#{anchor})")
    lines.append("\n---\n")

    # 1. Overview
    lines.append("## Company Overview\n")
    table_rows = [
        ("**Company**", report.get("company_name")),
        ("**Founded**", report.get("founding_year")),
        ("**Headquarters**", report.get("hq_location")),
        ("**Industry**", report.get("industry")),
        ("**Company Size**", report.get("company_size")),
        ("**Stock Ticker**", report.get("stock_ticker")),
        ("**Website**", report.get("logo_url")),
    ]
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    for k, v in table_rows:
        if v:
            lines.append(f"| {k} | {v} |")
    lines.append("")

    # 2. Leadership
    lines.append("## Founders & Leadership\n")
    if report.get("ceo"):
        lines.append(f"**CEO:** {report['ceo']}\n")
    founders = report.get("founders") or []
    if founders:
        lines.append("**Founders:**")
        for f in founders:
            lines.append(f"- {f}")
        lines.append("")
    c_suite = report.get("c_suite") or []
    if c_suite:
        lines.append("**C-Suite & Key Leadership:**")
        for p in c_suite:
            lines.append(f"- {p}")
        lines.append("")

    # 3. History
    lines.append("## Origin Story & Timeline\n")
    if report.get("origin_story"):
        lines.append("### Origin Story\n")
        lines.append(report["origin_story"])
        lines.append("")
    timeline = report.get("growth_timeline") or []
    if timeline:
        lines.append("### Growth Timeline\n")
        lines.append("| Year | Milestone |")
        lines.append("|------|-----------|")
        for item in timeline:
            lines.append(f"| **{item.get('year','')}** | {item.get('event','')} |")
        lines.append("")

    # 4. Challenges
    challenges = report.get("past_challenges") or []
    if challenges:
        lines.append("## Past Challenges\n")
        for item in challenges:
            lines.append(f"### {item.get('challenge','')}\n")
            lines.append(f"**Resolution:** {item.get('resolution','')}\n")

    # 5. Current projects
    current = report.get("current_projects") or []
    if current:
        lines.append("## Current Projects\n")
        for item in current:
            lines.append(f"### {item.get('name','')}\n")
            lines.append(f"{item.get('description','')}\n")

    # 6. Roadmap
    roadmap = report.get("future_roadmap") or []
    if roadmap:
        lines.append("## Future Roadmap\n")
        for item in roadmap:
            tl = item.get("timeline","")
            suffix = f" *(Expected: {tl})*" if tl else ""
            lines.append(f"### {item.get('initiative','')}{suffix}\n")
            lines.append(f"{item.get('description','')}\n")

    # 7. Competition
    competitors = report.get("competitors") or []
    differentiators = report.get("differentiators") or []
    if competitors or differentiators:
        lines.append("## Competitive Landscape\n")
        for item in competitors:
            lines.append(f"**vs. {item.get('name','')}:** {item.get('comparison','')}\n")
        if differentiators:
            lines.append("### Key Differentiators\n")
            for d in differentiators:
                lines.append(f"- {d}")
            lines.append("")

    # 8. Success stories
    stories = report.get("struggles_turned_success") or []
    if stories:
        lines.append("## Struggles Turned Success\n")
        for item in stories:
            lines.append(f"### {item.get('project','')}\n")
            lines.append(f"**Struggle:** {item.get('struggle','')}\n")
            lines.append(f"**Outcome:** {item.get('outcome','')}\n")

    # 9. Interview prep
    questions = report.get("interview_questions") or []
    if questions:
        lines.append("## Interview Preparation\n")
        lines.append("> Real questions asked at this company\n")
        by_cat: Dict[str, list] = {}
        for q in questions:
            by_cat.setdefault(q.get("category","General"), []).append(q)
        for cat, qs in by_cat.items():
            lines.append(f"### {cat}\n")
            for item in qs:
                lines.append(f"**Q: {item.get('question','')}**")
                if item.get("tip"):
                    lines.append(f"> 💡 *{item['tip']}*")
                lines.append("")

    # 10. Culture
    ci = report.get("culture_insights") or {}
    if ci:
        lines.append("## Culture & Work Environment\n")
        for label, key in [
            ("Work-Life Balance", "work_life_balance"),
            ("Innovation Style", "innovation_style"),
            ("Career Growth", "career_growth"),
            ("Team Environment", "team_environment"),
        ]:
            val = ci.get(key)
            if val:
                lines.append(f"**{label}:** {val}\n")
        perks = ci.get("notable_perks") or []
        if perks:
            lines.append("**Notable Perks:**")
            for p in perks:
                lines.append(f"- {p}")
            lines.append("")

    # 11. Red flags
    flags = report.get("red_flags") or []
    if flags:
        lines.append("## Red Flags & Due Diligence\n")
        lines.append("> ⚠ Investigate these before accepting an offer\n")
        for f in flags:
            lines.append(f"- ⚠ {f}")
        lines.append("")

    # 12. Application strategy
    strategy = report.get("application_strategy","")
    tips = report.get("insider_tips") or []
    if strategy or tips:
        lines.append("## Application Strategy\n")
        if strategy:
            lines.append(f"{strategy}\n")
        if tips:
            lines.append("### Insider Tips\n")
            for tip in tips:
                lines.append(f"- ✦ {tip}")
            lines.append("")

    # 13. Candidate fit
    lines.append("---\n")
    lines.append("## Candidate Fit Analysis\n")
    lines.append("> *Personalized based on the candidate's resume*\n")

    matching = report.get("matching_skills") or []
    if matching:
        lines.append("### Matching Skills\n")
        for skill in matching:
            lines.append(f"- {skill}")
        lines.append("")

    for key, label in [
        ("contribution_current", "Contribution to Current Projects"),
        ("contribution_future", "Impact on Future Roadmap"),
        ("competitive_advantage", "Competitive Advantage"),
        ("hiring_case", "Why This Company Should Hire This Candidate"),
    ]:
        val = report.get(key)
        if val:
            lines.append(f"### {label}\n")
            lines.append(f"{val}\n")

    lines.append("\n---")
    lines.append("*Report generated by [CompanyIQ](https://github.com/companyiq)*")
    return "\n".join(lines)
